# Grammar Definition
# Use the special keyword "EMPTY" to indicate an EMPTY/epsilon rule
# Comments start with "#" and cannot go on the same line as a rule
# Terminals are prefixed with _. Here is a full list of supported terminals:
# _Int8
# _Int16
# _Int32
# _Int64
# _Bool
# _Let
# _OpEquality
# _OpOr
# _OpAnd
# _OpNegate
# _OpAdd
# _OpMultiply
# _OpDivide
# _OpMod
# _OpAssign
# _LiteralInt
# _LiteralBool
# _Whitespace
# _Semicolon
# _Colon
# _Comma
# _OpenBrace
# _CloseBrace
# _OpenParen
# _CloseParen
# _OpenSquareBracket
# _CloseSquareBracket
# _OpenAngleBracket
# _CloseAngleBracket
# _Id

PrimitiveType   : _Int8 | _Int16 | _Int32 | _Int32 | _Int64 | _Bool;

# Top-level structure
Program         : TopLevelList;
TopLevelList    : TopLevel TopLevelList
                | EMPTY
                ;
TopLevel        : VarDefStatement
                ;

# Types
Type            : PrimitiveType | _Id;

# --- Variables ---
VarNameType         : _Id _Colon Type;
VarDefStatement     : _Let VarNameType _OpAssign ValueExpr _Semicolon;

# Expressions
ValueExpr       : HighExpr LowExprRest;
HighExpr        : ValueTerm HighExprRest;
HighExprRest    : HighExprOp HighExpr | EMPTY;
LowExprRest     : LowExprOp ValueExpr | EMPTY;

LowExprOp       : _OpAdd | _OpNegate | _OpOr | _OpAnd | _OpEquality;
HighExprOp      : _OpMultiply | _OpDivide | _OpMod;

ValueTerm       : _OpNot ValueTerm
                | _OpenParen ValueExpr _CloseParen
                | _LiteralBool
                | _LiteralInt
                | _Id
                ;