# Grammar Definition
# Use the special keyword "EMPTY" to indicate an EMPTY/epsilon rule
# Comments start with "#"
# Terminals are prefixed with _. Here is a full list of supported terminals:
# _Int8
# _Int16
# _Int32
# _Int64
# _Bool
# _Void
# _Let
# _While
# _Func
# _SmallArrow
# _OpEquality
# _OpOr
# _OpAnd
# _OpNegate
# _OpAdd
# _OpMultiply
# _OpDivide
# _OpMod
# _OpAssign
# _LiteralInt
# _LiteralBool
# _Whitespace
# _Semicolon
# _Colon
# _Comma
# _OpenBrace
# _CloseBrace
# _OpenParen
# _CloseParen
# _OpenSquareBracket
# _CloseSquareBracket
# _OpenAngleBracket
# _CloseAngleBracket
# _Id

PrimitiveType   : _Int8 | _Int16 | _Int32 | _Int32 | _Int64 | _Bool;
Type            : PrimitiveType | _Id;

# Top-level structure
Program             : ClassFuncFieldList;
ClassFuncFieldList  : ClassFuncField ClassFuncFieldList
                    | EMPTY
                    ;
ClassFuncField      : FunctionDef;

# Variables
VarNameType         : _Id _Colon Type;
VarDefStatement     : _Let VarNameType _OpAssign ValueExpr _Semicolon;

# Expressions
ValueExpr       : HighExpr LowExprRest;
HighExpr        : ValueTerm HighExprRest;
HighExprRest    : HighExprOp HighExpr | EMPTY;
LowExprRest     : LowExprOp ValueExpr | EMPTY;

LowExprOp       : _OpAdd | _OpNegate | _OpOr | _OpAnd | _OpEquality;
HighExprOp      : _OpMultiply | _OpDivide | _OpMod;

ValueTerm       : _OpNot ValueTerm
                | _OpenParen ValueExpr _CloseParen
                | _LiteralBool
                | _LiteralInt
                | _Id
                ;

# Functions
FunctionDef     : _Func _Id  ParamList ReturnTypeDef Block;
ParamList       : _OpenParen ParamListStart _CloseParen
ParamListStart  : VarNameType ParamListRest | EMPTY*; # If EMPTY: Assumed to be []
ParamListRest   : _Comma ParamListStart     | EMPTY;
ReturnTypeDef   : _SmallArrow ReturnType    | EMPTY*; # If EMPTY: Assumed to be void
ReturnType      : _Void | Type;

# Control Statements
WhileStatement  : _While ValueExpr Block;



StatementBlock  : VarDefStatement
                | WhileStatement
                | StatementBlock
                | EmptyStatement
                ;
EmptyStatement  : _Semicolon;